// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	policlinic "github.com/KamarRS-App/KamarRS-App/features/policlinic"
	mock "github.com/stretchr/testify/mock"
)

// PoliclinicRepo is an autogenerated mock type for the RepositoryInterface type
type PoliclinicRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *PoliclinicRepo) Create(input policlinic.CorePoliclinic) (int, error) {
	ret := _m.Called(input)

	var r0 int
	if rf, ok := ret.Get(0).(func(policlinic.CorePoliclinic) int); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(policlinic.CorePoliclinic) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *PoliclinicRepo) Delete(id int) (int, error) {
	ret := _m.Called(id)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *PoliclinicRepo) GetAll() ([]policlinic.CorePoliclinic, error) {
	ret := _m.Called()

	var r0 []policlinic.CorePoliclinic
	if rf, ok := ret.Get(0).(func() []policlinic.CorePoliclinic); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]policlinic.CorePoliclinic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllbyHospitalID provides a mock function with given fields: limit, offset, id
func (_m *PoliclinicRepo) GetAllbyHospitalID(limit int, offset int, id int) ([]policlinic.CorePoliclinic, int, error) {
	ret := _m.Called(limit, offset, id)

	var r0 []policlinic.CorePoliclinic
	if rf, ok := ret.Get(0).(func(int, int, int) []policlinic.CorePoliclinic); ok {
		r0 = rf(limit, offset, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]policlinic.CorePoliclinic)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(int, int, int) int); ok {
		r1 = rf(limit, offset, id)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(int, int, int) error); ok {
		r2 = rf(limit, offset, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetById provides a mock function with given fields: id
func (_m *PoliclinicRepo) GetById(id int) (policlinic.CorePoliclinic, error) {
	ret := _m.Called(id)

	var r0 policlinic.CorePoliclinic
	if rf, ok := ret.Get(0).(func(int) policlinic.CorePoliclinic); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(policlinic.CorePoliclinic)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: input, id
func (_m *PoliclinicRepo) Update(input policlinic.CorePoliclinic, id int) error {
	ret := _m.Called(input, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(policlinic.CorePoliclinic, int) error); ok {
		r0 = rf(input, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPoliclinicRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewPoliclinicRepo creates a new instance of PoliclinicRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPoliclinicRepo(t mockConstructorTestingTNewPoliclinicRepo) *PoliclinicRepo {
	mock := &PoliclinicRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
